name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Jab aap main branch me code push karenge tab ye chalega

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub se project code fetch karna
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. GitHub Secrets wale credentials se Docker Hub me login karna
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker Image build karke Docker Hub par push karna
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ssaud12344/student-ms-api:latest